from .animal import Animal
from .complete_animals.river_dolphin import RiverDolphin
from .contains_animals import IContainsAnimals
from .complete_animals.goose import Goose
from .complete_animals.spider import Spider
from .complete_animals.kikakapu import Kikakapu
from .complete_animals.gecko import Gecko
from .complete_animals.opeapea import Opeapea
from .complete_animals.pueo import Pueo
from .complete_animals.ulae import Ulae
